version: '3.8'

# Development overrides
services:
  api-gateway:
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  identity-api:
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  athletes-api:
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  workouts-api:
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  exercises-api:
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  dashboard-api:
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  media-api:
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  communication-api:
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
